name: "Setup eget"
description: "Setup zyedidia/eget CLI tool and add it to the PATH"

runs:
  using: "composite"
  steps:
    - name: Setup eget
      shell: bash
      env:
        EGET_DIR: ${{github.workspace}}/.eget
        EGET_CONFIG: ${{github.workspace}}/.eget/.eget.toml
      run: |
        if test -f $EGET_CONFIG; then
          exit 0
        fi

        curl https://zyedidia.github.io/eget.sh | sh
        mkdir -p $EGET_DIR && mv eget $EGET_DIR
        DIR=$(readlink -f $EGET_DIR) # workaround for windows + toml
        printf "[global]\ntarget='$DIR'\nquiet=true\ngithub_token='${{ github.token }}'\n" > $EGET_CONFIG
        echo $EGET_DIR >> $GITHUB_PATH
        echo "EGET_CONFIG=$EGET_CONFIG" >> $GITHUB_ENV
